# .github/workflows/test-connection.yml

name: 'Test Supabase DB Connection'

on:
  # Allows you to run it manually from the Actions tab
  workflow_dispatch:

jobs:
  test-db-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: 'Attempt to Connect to DB'
        run: |
          echo "Attempting to push to the database..."
          supabase db push --db-url "${{ secrets.TEST_SUPABASE_DB_URL }}"
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }} # Note: This is not needed for db push, but good practice